### ISSUE TITLE
1.7.3 not covering `.lista_related a[href^="/torrent/"]` related torrent list

### ISSUE THREAD

**Issue by hedcet** [PeratX/RARBGHelper#15]
pls revert back the changes in this commit https://github.com/PeratX/RARBGHelper/commit/49db5b1d453417cd11eb28e6ea88a218ac2dfdc9

it fails to color opened/viewed links in related torrent list inside individual page like [this](https://rarbgp2p.org/torrent/8uvlgf4)
<img width="677" alt="Screenshot 2022-05-29 at 5 57 59 PM" src="https://user-images.githubusercontent.com/1794209/170868376-7f22ae3a-c1de-4ee0-8e9b-6f6b783d76bd.png">

**Comment by hedcet** [comment]
1.7.2 it will color opened/viewed torrent links like below
<img width="716" alt="Screenshot 2022-05-29 at 6 02 50 PM" src="https://user-images.githubusercontent.com/1794209/170868546-e41def65-4320-4c6f-83ab-0fb8e21d5e52.png">

**Comment by hedcet** [comment]
1.7.2 if its failing in any situation pls provide me a reproduction

**Comment by PeratX** [comment]
failed in top100/top10 pages
chrome 101

**Comment by hedcet** [comment]
trying to fix this with PR https://github.com/PeratX/RARBGHelper/pull/19
