### ISSUE TITLE
大图预览还更新吗

### ISSUE THREAD

**Issue by 7peanuts** [PeratX/RARBGHelper#22]
大佬最近还更新吗？大图预览好像不行了，我添加了 @match 规则还是不行。

**Comment by PeratX** [comment]
亲测可用

**Comment by 7peanuts** [comment]
找到原因了，关掉脚本 [自动无缝翻页](https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5) 后可以显示了

另外在这个页面还是不显示
https://rargb.to/
