### ISSUE TITLE
rarbg blocked

### ISSUE THREAD

**Issue by monelge** [PeratX/RARBGHelper#9]
We have too many requests from your ip in the past 24h.
Im sorry but we cannot process your request right now.
Your ip xxx.xxx.xxx.xxx is temporary banned for 2 hours.
Please contact an administrator immediately at support@rarbg.com if you think this is a mistake!
This limit can happen if any of the following conditions exist :
You are using a Proxy/Webproxy that is abused on our site
You are using a VPN that is abused on our site
Your browser has addons that are adware
Your pc is acting as a proxy to other networks
You dont have javascript or cookies enabled
You have a virus and your ip is listed in ProjectHoneypot
You are making more than 10 requests per second to the site

**Comment by PeratX** [comment]
Remember not to scroll too quick over the link, because this will trigger many request to rarbg which will cause the blocking.
